In [1]:
import pandas as pd 
from pathlib import Path 

import os

In [4]:
print(os.getcwd())

e:\project_archive\student-dropout-enrolled-graduate-rate-prediction

In [3]:
os.chdir("..")

In [5]:
X_test_path = Path("data/processed/X_test.csv")

if not X_test_path.exists():
    raise FileExistsError()

In [6]:
df = pd.read_csv(X_test_path, sep=';')
df.head()

,Marital status,Application mode,Application order,Course,Previous qualification,Previous qualification (grade),Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Inflation rate
0,4,39,1,9130,1,133.1,3,1,5,5,...,0,1,0,1,30,6,7,0,0.000000,0.6
1,1,17,1,9238,1,125.0,4,3,1,1,...,0,1,0,0,18,6,9,5,11.571429,0.3
2,1,17,1,9853,1,133.0,38,38,9,9,...,1,1,0,1,18,7,7,7,12.714286,0.3
3,1,17,2,9670,1,110.0,1,1,4,10,...,0,1,1,0,19,6,8,6,13.857143,2.8
4,1,39,1,9500,1,130.0,37,19,9,8,...,0,1,0,0,27,7,14,0,0.000000,0.6

In [14]:
import random 

SIZE = len(df)

samples = random.sample(range(SIZE), 10)
# print(samples)

sample_df = df.iloc[samples, :].copy()
sample_df

,Marital status,Application mode,Application order,Course,Previous qualification,Previous qualification (grade),Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Inflation rate
513,1,39,1,9130,1,133.1,1,1,90,1,...,1,0,1,0,41,5,5,0,0.000000,3.7
42,1,16,1,9085,1,140.0,1,1,9,9,...,0,1,0,0,18,5,8,4,13.250000,3.7
234,2,43,1,9991,1,134.0,37,37,9,9,...,0,1,0,0,32,5,5,5,10.200000,-0.8
474,1,1,5,9500,1,139.0,38,37,7,7,...,0,1,0,1,18,8,8,8,13.435000,-0.8
158,1,1,1,9254,1,133.1,38,19,3,3,...,0,1,0,0,21,6,16,2,11.000000,3.7
723,1,1,1,9238,1,116.0,38,38,9,8,...,0,1,1,0,18,6,9,5,11.000000,0.6
75,1,1,1,171,1,163.0,19,1,9,7,...,0,1,1,0,18,0,0,0,0.000000,-0.8
323,2,39,1,9003,1,133.1,19,19,4,4,...,0,0,0,0,35,6,0,0,0.000000,2.8
370,1,1,4,9500,1,126.0,19,19,9,9,...,0,1,0,0,19,7,8,6,11.658333,0.5
649,1,43,1,9853,1,110.0,37,37,9,9,...,1,0,0,0,28,6,0,0,0.000000,1.4

In [16]:
TEST_SAMPLE_PATH = Path("data")

if not TEST_SAMPLE_PATH.exists():
    raise FileExistsError()

sample_df.to_csv(TEST_SAMPLE_PATH / "test_sample.csv", sep=';')